apiVersion: v1
kind: Service
metadata:
  name: vector-app-argocd
  namespace: default
  labels:
    app: vector-app-argocd
    managed-by: argocd
spec:
  selector:
    app: vector-app-argocd
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30089
  type: NodePort
