apiVersion: v1
kind: Service
metadata:
  name: vector-app-argocd
  namespace: default
  labels:
    managed-by: argocd
spec:
  selector:
    app: vector-app-argocd
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP